### ISSUE TITLE
head tag missing

### ISSUE THREAD

**Issue by karankartikeya** [LockedUp-Coders/activity#17]
https://github.com/LockedUp-Coders/activity/blob/4479ea630b60228b4cff0b95b9dbf413c0dff977/week1/frontend/rajat_mehta.html#L6

**Comment by YashKumarVerma** [comment]
@imrajatmehta updates ?

**Comment by imrajatmehta** [comment]
i didnt got any notification about this pull request i will update it

**Comment by imrajatmehta** [comment]
@YashKumarVerma i saw my code it is updated. by you so which update are you asking?

**Comment by YashKumarVerma** [comment]
@karankartikeya can you explain as you opened this issue ?

**Comment by karankartikeya** [comment]
Earlier the code missed the  head tag according to me, maybe i would have missed it while reviewing it. I apologise for the mistake.
